version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: keeptrip_test

    environment:
      NODE_ENV: testing

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Check TS types
          command: npm run server-check-types
      
      - run:
          name: Run database migrations
          command: npm run migrations:run
      
      - run:
          name: Run linter
          command: npm run lint
      
      - run:
          name: Run tests
          command: npm run test